### ISSUE TITLE
Add basic git workflow

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/dt-backend-services#14]
Currently, there is no workflow specified in this repository that could check code quality, formatting, tests, commitlint same as edX.

Acceptance Criteria:
- [x] Add basic GitHub actions workflow file
- [x] Add code quality e.g. pycode style, black etc #5 
- [ ] Run tests in the workflow (pytest/tox) #5 
- [ ] Add coverage Github Action #5 
- [x] Add commitlint just like edX #4

**Comment by BbrSofiane** [comment]
Need to do more work on dependency resolution to be able to run tests and services with pants. Closing this issue and opening a new specific issue for this.
